services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - resources_default

networks:
  resources_default:
    external: true
